version: '3.8'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: appcompleto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: camilo1998
    ports:
      - "5432:5432"

  server:
    build: ./Server
    depends_on:
      - database
    links:
      - database
    ports:
      - 3000:3000
